# Generated by Django 4.2.29 on 2026-03-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('trigger_name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EntityBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('jem_file_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('body_data', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'entity bodies',
            },
        ),
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('jpm_path', models.CharField(max_length=300)),
                ('part_data', models.JSONField()),
                ('attachment_meta', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VariantPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pack.modelpart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pack.carvariant')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('variant', 'part')},
            },
        ),
        migrations.AddField(
            model_name='carvariant',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pack.entitybody'),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='parts',
            field=models.ManyToManyField(blank=True, through='pack.VariantPart', to='pack.modelpart'),
        ),
    ]
