# Generated by Django 4.2.29 on 2026-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0003_partslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariant',
            name='texture_override',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='partslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
