textures.1=1
name.1=DEFAULT

textures.2=2
name.2=mc50701

textures.3=3
name.3=leader0701

textures.4=4
name.4=360sx0701

textures.5=5
name.5=leader0703

textures.6=6
name.6=leader0702

textures.7=7
name.7=