textures.1=1
name.1=DEFAULT

textures.2=2
name.2=mc50707

textures.3=3
name.3=mc50708

textures.4=4
name.4=leader0705

textures.5=5
name.5=leader0706

textures.6=6
name.6=mc50706

textures.7=7
name.7=leader0704

textures.8=8
name.8=mc50705

textures.9=9
name.9=360sx0704

textures.10=10
name.10=33_intermediate
