"""
python manage.py export_pack

Regenerates all .jem, .jpm, and .properties files in PACK_ROOT
from the current database state. Safe to run repeatedly.
"""

import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from pack.models import EntityBody, ModelPart, CarVariant, VariantPart


class Command(BaseCommand):
    help = 'Write pack files from the database to PACK_ROOT'

    def handle(self, *args, **options):
        pack_root = Path(settings.PACK_ROOT)
        cem_dir = pack_root / 'assets' / 'minecraft' / 'optifine' / 'cem'

        # Write .jpm files
        for part in ModelPart.objects.all():
            rel = part.jpm_path.split('optifine/cem/', 1)[-1]
            out_path = cem_dir / rel
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(
                json.dumps(part.part_data, indent='\t'), encoding='utf-8'
            )
            self.stdout.write(f'  Wrote {rel}')

        # Write .jem files and group by body for .properties
        bodies: dict[int, list[CarVariant]] = {}
        for variant in CarVariant.objects.all().order_by('order'):
            _write_jem(cem_dir, variant)
            self.stdout.write(f'  Wrote {variant.file_name}.jem')
            bodies.setdefault(variant.body_id, []).append(variant)

        # Write .properties files
        for body_id, variants in bodies.items():
            body = EntityBody.objects.get(pk=body_id)
            _write_properties(cem_dir, body, variants)
            self.stdout.write(f'  Wrote {body.jem_file_name}.properties')

        self.stdout.write(self.style.SUCCESS('Export complete.'))


def _write_jem(cem_dir: Path, variant: CarVariant):
    jem = json.loads(json.dumps(variant.body.body_data))

    attachments = []
    for vp in VariantPart.objects.filter(variant=variant).order_by('order'):
        entry = dict(vp.part.attachment_meta)
        entry['model'] = vp.part.jpm_path
        attachments.append(entry)

    if attachments:
        jem['models'] = [jem['models'][0]] + attachments + jem['models'][1:]

    out_path = cem_dir / f'{variant.file_name}.jem'
    out_path.write_text(json.dumps(jem, indent='\t'), encoding='utf-8')


def _write_properties(cem_dir: Path, body: EntityBody, variants: list):
    triggered = sorted(
        [v for v in variants if v.trigger_name], key=lambda v: v.order
    )
    if not triggered:
        return

    lines = ['# Auto-generated by Garage64 editor\n']
    for v in triggered:
        lines.append(f'models.{v.order}={v.order + 1}\n')
        lines.append(f'name.{v.order}={v.trigger_name}\n')

    props_path = cem_dir / f'{body.jem_file_name}.properties'
    props_path.write_text(''.join(lines), encoding='utf-8')
