textures.1=1
name.1=DEFAULT

textures.2=2
name.2=leader0709

textures.3=3
name.3=leader0707

textures.4=4
name.4=leader0708

textures.5=5
name.5=leader0710

textures.6=6
name.6=360sx0706

textures.7=7
name.7=360sx0707

textures.8=8
name.8=360sx0705