textures.1=1
name.1=DEFAULT

textures.2=2
name.2=leader0713

textures.3=3
name.3=360sx0711

textures.4=4
name.4=leader0712

textures.5=5
name.5=mc50712

textures.6=6
name.6=360sx0712

textures.7=7
name.7=Solara

textures.8=8
name.8=Solara32